services:
  metastore:
    image: postgres:11
    hostname: metastore
    environment:
      POSTGRES_PASSWORD: jupyter
    volumes:
      - metastore:/var/lib/postgresql/data
      - ./ddl/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always
    network_mode: "host"

  master:
    image: hadoop-hive-spark-master
    hostname: master
    depends_on:
      - metastore
    environment:
      SPARK_MASTER_HOST: 172.28.1.2
      SPARK_LOCAL_IP: 172.28.1.2
      SPARK_LOCAL_HOSTNAME: master.net
    volumes:
      - namenode:/opt/hadoop/dfs/name
    restart: always
    network_mode: "host"
    extra_hosts:
      - "metastore:127.0.0.1"
      - "worker1:woeker1.net"

volumes:
  namenode:
  namesecondary:
  datanode1:
  datanode2:
  metastore: